/**
 * LA CAVA NOIRE // Catálogo Exclusivo de Quesos de Autor y Afinación
 * Todos los precios expresados en Pesos Chilenos ($ CLP) con IVA incluido.
 */

const CHEESE_PRODUCTS = [
  {
    id: "comte-36m",
    name: "Comté Extra Réserve AOP (36 Meses)",
    subtitle: "Afinado en las cavas subterráneas del Fort Saint-Antoine, Jura",
    origin: "Franco-Condado, Francia",
    appellation: "AOP (Appellation d'Origine Protégée)",
    category: "pasta-dura",
    categoryLabel: "Pasta Prensada Cocida",
    aging: "36 Meses de Cava",
    milkType: "Leche cruda de vaca Montbéliarde",
    intensity: 4,
    acidity: 55,
    acidityLabel: "55% (Acidez láctica noble y equilibrada)",
    intensityScore: 85,
    intensityScoreLabel: "85% (Sabor profundo a avellana tostada)",
    creaminess: 45,
    creaminessLabel: "45% (Firme con cristales crocantes de tirosina)",
    salinity: 60,
    salinityLabel: "60% (Salazón justa y mineral)",
    weight: "250g (Cuña seleccionada a mano)",
    price: 29990,
    badge: "Reserva de Oro",
    easyGuide: "Queso francés de vaca muy madurado (3 años). Es consistente y durito, con pequeños cristalitos crujientes deliciosos. Su sabor recuerda a frutos secos y mantequilla dorada. No pica nada, es muy elegante y fácil de disfrutar.",
    description: "Una joya de la quesería gala. Elaborado exclusivamente en verano cuando las vacas pastan en alta montaña. Textura densa salpicada de cristales crocantes de tirosina. Notas complejas a avellana tostada, mantequilla noisette y toques sutiles de fruta deshidratada.",
    tastingNotes: {
      aroma: "Mantequilla tibia, frutos secos y sotobosque",
      palate: "Umami profundo, acidez láctica noble y dulzor de caramelo salino",
      texture: "Untuosa con cristales crujientes de aminoácidos"
    },
    accompaniment: "Nueces tostadas, uvas blancas frescas, higos secos y pan crujiente de masa madre horneado en leña.",
    serviceTemp: "16°C - 18°C",
    image: "img/products/comte-36m.jpg",
    imageHover: "img/products/comte-36m-hover.jpg",
    inStock: true
  },
  {
    id: "pecorino-tartufo",
    name: "Pecorino al Tartufo Nero Riserva",
    subtitle: "Elaboración toscana con virutas visibles de Tuber Melanosporum",
    origin: "Toscana / Umbría, Italia",
    appellation: "DOP Tradizionale",
    category: "trufados",
    categoryLabel: "Quesos Trufados",
    aging: "12 Meses",
    milkType: "100% Leche cruda de oveja de pasto",
    intensity: 5,
    acidity: 45,
    acidityLabel: "45% (Baja y aromática, predomina la trufa)",
    intensityScore: 95,
    intensityScoreLabel: "95% (Máxima potencia terrosa de trufa negra)",
    creaminess: 60,
    creaminessLabel: "60% (Firme pero mantecoso al morder)",
    salinity: 75,
    salinityLabel: "75% (Salinidad italiana sabrosa)",
    weight: "220g (Corte en cuña sellada al vacío)",
    price: 34990,
    badge: "Colección Privada",
    easyGuide: "Queso italiano de pura oveja con auténtica trufa negra rallada en su interior. Tiene un aroma intenso y un sabor sabroso que llena toda la boca. Exquisito con una cucharadita de miel o pan caliente.",
    description: "Obra maestra italiana que fusiona la leche grasa de ovejas sienesas con auténtica trufa negra recolectada a mano. La pasta es compacta, marfilada y generosamente veteada con finas lascas de trufa que inundan el paladar de elegancia terrosa y notas boscosas.",
    tastingNotes: {
      aroma: "Trufa negra salvaje, tierra húmeda y cuero fino",
      palate: "Intenso, sápido, con un final prolongado y untuoso",
      texture: "Firme pero mantecosa al fundirse en boca"
    },
    accompaniment: "Miel con trufa blanca, peras maduras laminadas y pan de centeno campesino.",
    serviceTemp: "18°C",
    image: "img/products/pecorino-tartufo.jpg",
    imageHover: "img/products/pecorino-tartufo-hover.jpg",
    inStock: true
  },
  {
    id: "parmigiano-vacche-rosse",
    name: "Parmigiano Reggiano Vacche Rosse (30 Meses)",
    subtitle: "Raza autóctona 'Rossa Reggiana' de altísima caseína",
    origin: "Reggio Emilia, Italia",
    appellation: "DOP Vacche Rosse",
    category: "pasta-dura",
    categoryLabel: "Pasta Prensada Cocida",
    aging: "30 Meses",
    milkType: "Leche cruda de vaca Reggiana",
    intensity: 4,
    acidity: 50,
    acidityLabel: "50% (Fresca y armónica, sin asperezas)",
    intensityScore: 82,
    intensityScoreLabel: "82% (Gran riqueza de umami y piña madura)",
    creaminess: 30,
    creaminessLabel: "30% (Granuloso, cruje y se funde en saliva)",
    salinity: 68,
    salinityLabel: "68% (Sápido y mineral noble)",
    weight: "300g (Bloque quebrado artesanal)",
    price: 31990,
    badge: "DOP Histórica",
    easyGuide: "El parmesano más exclusivo de Italia, hecho con leche de vacas rojas especiales. No es duro ni gomoso: se quiebra en la boca como una galleta de queso con recuerdos a fruta y mantequilla.",
    description: "El auténtico padre de los Parmesanos. La vaca roja produce solo la mitad de leche que otras razas, pero con una concentración proteica y enzimática insuperable. Se parte con punzón en rocas granulosas con aromas a piña madura, heno seco y caldo de ternera concentrado.",
    tastingNotes: {
      aroma: "Heno maduro, fruta confitada y crema tostada",
      palate: "Explosión mineral, sapidez perfectamente equilibrada sin asperezas",
      texture: "Granulosa, crujiente y soluble"
    },
    accompaniment: "Gotas de vinagre balsámico tradicional de Módena, nueces tostadas o higos maduros.",
    serviceTemp: "17°C",
    image: "img/products/parmigiano-vacche-rosse.jpg",
    imageHover: "img/products/parmigiano-vacche-rosse-hover.jpg",
    inStock: true
  },
  {
    id: "brillat-savarin-creme",
    name: "Brillat-Savarin Triple Crème Affiné",
    subtitle: "Enriquecido con nata fresca y corteza de Penicillium Camemberti",
    origin: "Normandía / Borgoña, Francia",
    appellation: "IGP Artisanale",
    category: "corteza-enmohecida",
    categoryLabel: "Pasta Blanda Enmohecida",
    aging: "5 Semanas",
    milkType: "Leche entera de vaca pasteurizada + Nata doble",
    intensity: 2,
    acidity: 72,
    acidityLabel: "72% (Acidez refrescante tipo yogurt natural)",
    intensityScore: 40,
    intensityScoreLabel: "40% (Suave, delicado y mantecoso)",
    creaminess: 98,
    creaminessLabel: "98% (¡Pura crema! Se unta como mousse)",
    salinity: 35,
    salinityLabel: "35% (Muy suave en sal)",
    weight: "200g (Medio disco)",
    price: 24990,
    badge: "Alta Cremor",
    easyGuide: "El queso más cremoso de Francia. Parece una crema de mantequilla o mousse dulce-salada con corteza blanca aterciopelada. Es suave, fresco, nada invasivo y perfecto para untar en galletas o pan.",
    description: "Bautizado en honor al célebre gastrónomo Jean Anthelme Brillat-Savarin. Posee un 72% de materia grasa que le otorga una consistencia cercana a una mousse de mantequilla de lujo, con sutiles toques a champiñón de París fresco y acidez láctica refrescante.",
    tastingNotes: {
      aroma: "Lactosa fresca, nata batida y setas blancas",
      palate: "Suntuoso, fundente, con balance cítrico ligero",
      texture: "Aterciopelada, sedosa y untuosa"
    },
    accompaniment: "Frutos rojos frescos (frambuesas o fresas), tostadas finas y mermelada artesanal de higos.",
    serviceTemp: "14°C - 16°C",
    image: "img/products/brillat-savarin.jpg",
    imageHover: "img/products/brillat-savarin-hover.jpg",
    inStock: true
  },
  {
    id: "chiloe-oveja-niebla",
    name: "Queso de Oveja Chiloé 'Reserva Marina' (12M)",
    subtitle: "Afinado frente al Pacífico en la Isla Grande de Chiloé",
    origin: "Chiloé, Los Lagos, Chile",
    appellation: "Quesería de Autor Chilena",
    category: "de-autor",
    categoryLabel: "De Autor Chileno",
    aging: "12 Meses",
    milkType: "Leche cruda de oveja de praderas marinas",
    intensity: 4,
    acidity: 58,
    acidityLabel: "58% (Toque láctico limpio del sur)",
    intensityScore: 82,
    intensityScoreLabel: "82% (Sabor silvestre y frutos secos)",
    creaminess: 50,
    creaminessLabel: "50% (Pasta firme con grasa noble)",
    salinity: 72,
    salinityLabel: "72% (Salinidad marina de Chiloé)",
    weight: "250g (Cuña numerada)",
    price: 27990,
    badge: "Producción Chilena Limitada",
    easyGuide: "El gran orgullo quesero del sur de Chile. Proviene de ovejas que pastan a orillas del mar en Chiloé. Tiene un sabor campestre delicioso con un suave toque salino de la brisa marina. Muy sabroso y natural.",
    description: "El orgullo de la afinación chilena austral. Las ovejas pastan a metros del mar en praderas impregnadas de salmuera y algas. Curado en tablas de roble pellín en cava húmeda, ofrece notas salobres, tostadas y un perfil vegetal herbáceo inigualable.",
    tastingNotes: {
      aroma: "Hierba húmeda, brisa marina, almendras tostadas",
      palate: "Punzante mineralidad marina, final cálido y láctico persistente",
      texture: "Quebradiza y compacta con grasa noble de oveja"
    },
    accompaniment: "Dulce de membrillo artesanal chileno, manzanas verdes en láminas y frutos secos del sur.",
    serviceTemp: "17°C",
    image: "img/products/chiloe-oveja.jpg",
    imageHover: "img/products/chiloe-oveja-hover.jpg",
    inStock: true
  },
  {
    id: "roquefort-societe",
    name: "Roquefort AOP 'Caves Baragnaudes'",
    subtitle: "El rey de los quesos azules afinado en las fallas del Combalou",
    origin: "Aveyron, Occitania, Francia",
    appellation: "AOP d'Origine Contrôlée",
    category: "quesos-azules",
    categoryLabel: "Quesos Azules Nobles",
    aging: "5 Meses en cueva natural",
    milkType: "Leche cruda de oveja Lacaune",
    intensity: 5,
    acidity: 65,
    acidityLabel: "65% (Viva y punzante)",
    intensityScore: 98,
    intensityScoreLabel: "98% (Máxima potencia azul noble)",
    creaminess: 80,
    creaminessLabel: "80% (Húmedo, untuoso y mantecoso)",
    salinity: 88,
    salinityLabel: "88% (Salazón marcada tradicional)",
    weight: "180g (Corte especial)",
    price: 26990,
    badge: "Mítico AOP",
    easyGuide: "El clásico queso azul francés de oveja, madurado en cuevas naturales de piedra. Es cremoso, húmedo, con vetas azules de sabor fuerte e inconfundible. Exquisito con un toque de miel o uvas dulces.",
    description: "Venerado desde la época de Carlomagno. El hongo noble Penicillium roqueforti se desarrolla de forma salvaje gracias a la ventilación de las 'fleurines' de las cuevas de Roquefort. Pasta marfil con vetas azul esmeralda, textura fundente y un perfil sápido y potente.",
    tastingNotes: {
      aroma: "Humedad de cueva caliza, salitre y sotobosque",
      palate: "Intenso, salado, picante refinado con dulzor cárnico",
      texture: "Cremosa, húmeda y granulada en vetas"
    },
    accompaniment: "Miel pura de ulmo chilena, peras asadas, damascos deshidratados y crackers de avena.",
    serviceTemp: "15°C",
    image: "img/products/roquefort-societe.jpg",
    imageHover: "img/products/roquefort-societe-hover.jpg",
    inStock: true
  },
  {
    id: "gouda-vintage-5a",
    name: "Gouda Boerenkaas Millésime (5 Años)",
    subtitle: "Elaborado en granja con cristales dorados de maduración extrema",
    origin: "Holanda Meridional, Países Bajos",
    appellation: "Boerenkaas GTS (Especialidad Tradicional Garantizada)",
    category: "pasta-dura",
    categoryLabel: "Pasta Prensada Cocida",
    aging: "60 Meses (5 Años)",
    milkType: "Leche cruda de vaca de pastizal holandés",
    intensity: 5,
    acidity: 40,
    acidityLabel: "40% (Baja, notas dulces de caramelo toffee)",
    intensityScore: 94,
    intensityScoreLabel: "94% (Gran concentración de sabor caramelizado)",
    creaminess: 25,
    creaminessLabel: "25% (Roca dura y densamente cristalizada)",
    salinity: 70,
    salinityLabel: "70% (Cristales salinos dulces)",
    weight: "250g (Corte en roca)",
    price: 33990,
    badge: "Afinación Centenaria",
    easyGuide: "Un Gouda holandés de 5 años de curación. Por fuera parece una piedra ámbar dorada. Al comerlo cruje como caramelo salado con notas a toffee y frutos secos. No es ácido ni amargo, es una delicia para picar.",
    description: "Una experiencia gastronómica que rivaliza con los mejores destilados. Cinco años de evaporación y cristalización confieren a este queso una tonalidad ámbar oscura casi translúcida. Cada bocado estalla en cristales crujientes de tirosina con recuerdos a caramelo quemado, toffee y frutos secos.",
    tastingNotes: {
      aroma: "Bourbon, melaza, nuez moscada y cuero curtido",
      palate: "Dulzura licorosa, umami arrollador y final mineral profundo",
      texture: "Dura, quebradiza y densamente cristalizada"
    },
    accompaniment: "Manzanas crujientes, almendras tostadas con sal de mar o higos negros caramelizados.",
    serviceTemp: "18°C",
    image: "img/products/gouda-vintage.jpg",
    imageHover: "img/products/gouda-vintage-hover.jpg",
    inStock: true
  },
  {
    id: "morbier-ceniza-aop",
    name: "Morbier AOP con Raya de Ceniza Vegetal",
    subtitle: "Doble cuajada tradicional con línea de carbón vegetal alimentario",
    origin: "Montañas del Jura, Francia",
    appellation: "AOP Contrôlée",
    category: "de-autor",
    categoryLabel: "Pasta Prensada No Cocida",
    aging: "100 Días",
    milkType: "Leche cruda de vaca",
    intensity: 3,
    acidity: 52,
    acidityLabel: "52% (Láctica suave y muy agradable)",
    intensityScore: 60,
    intensityScoreLabel: "60% (Sabor medio suave a mantequilla)",
    creaminess: 78,
    creaminessLabel: "78% (Tierna, elástica y fundente)",
    salinity: 48,
    salinityLabel: "48% (Punto salino muy moderado)",
    weight: "250g (Cuña)",
    price: 22990,
    badge: "Tradición Alpina",
    easyGuide: "Famoso por su línea negra en el medio (ceniza vegetal comestible). Es un queso francés suave, tierno, fácil de cortar y muy agradable al paladar. Agradable para toda la familia y perfecto para tablas de picoteo.",
    description: "Reconocible al instante por su línea horizontal de ceniza vegetal que históricamente separaba el ordeño de la mañana del de la tarde. Ofrece una corteza lavada anaranjada, pasta elástica y cremosa con sutiles toques afrutados y fondo de heno fresco.",
    tastingNotes: {
      aroma: "Heno fresco, establo dulce y fruta cocida",
      palate: "Láctico, mantecoso, con ligero amargor elegante de avellana",
      texture: "Elástica, suave y fundente en boca"
    },
    accompaniment: "Pepinillos encurtidos agridulces, pan campesino rústico y nueces.",
    serviceTemp: "16°C",
    image: "img/products/morbier-ceniza.jpg",
    imageHover: "img/products/morbier-ceniza-hover.jpg",
    inStock: true
  },
  {
    id: "tabla-degustacion-privee",
    name: "Cofre Degustación 'Grand Affineur' (5 Quesos)",
    subtitle: "Experiencia completa para 6 a 8 comensales en caja de madera de cedro",
    origin: "Selección Curada Europea & Chilena",
    appellation: "Reserva del Maestro Quesero",
    category: "tablas-degustacion",
    categoryLabel: "Cofres & Tablas de Autor",
    aging: "Afinaciones mixtas de 5 semanas a 36 meses",
    milkType: "Trilogía de Leches (Vaca Montbéliarde, Oveja Marina, Cabra de los Alpes)",
    intensity: 4,
    acidity: 62,
    acidityLabel: "62% (Armonía equilibrada)",
    intensityScore: 85,
    intensityScoreLabel: "85% (Recorrido de sabores suaves a intensos)",
    creaminess: 70,
    creaminessLabel: "70% (Variedad de texturas cremosas y duras)",
    salinity: 65,
    salinityLabel: "65% (Degustación guiada completa)",
    weight: "1.250g en total (5 quesos seleccionados + Acompañamientos)",
    price: 89990,
    badge: "Best Seller Exclusivo",
    easyGuide: "Caja de regalo de madera con 5 tipos de quesos de autor ya cortados y seleccionados, más miel de trufa, nueces y galletas. Es la opción más práctica si tienes invitados en casa: solo abrir y disfrutar.",
    description: "La cumbre de nuestra cava. Incluye 250g de Comté 36M, 200g de Brillat-Savarin Triple Crème, 220g de Pecorino al Tartufo, 180g de Roquefort Baragnaudes y 250g de Queso de Oveja Chiloé 12M. Acompañado de frasco de miel de trufa blanca de Alba (50g), nueces pecanas chilenas y crackers de masa madre al romero.",
    tastingNotes: {
      aroma: "Un viaje sensorial desde las flores alpinas hasta la trufa umbra",
      palate: "Recorrido armónico de menor a mayor intensidad gustativa",
      texture: "Desde la mousse sedosa hasta el cristal crujiente milenario"
    },
    accompaniment: "Tabla lista para servir con miel con trufa blanca, nueces pecanas y crackers de masa madre al romero.",
    serviceTemp: "Retirar del refrigerador 45 min antes de servir",
    image: "img/products/tabla-degustacion.jpg",
    imageHover: "img/products/tabla-degustacion-hover.jpg",
    inStock: true
  }
];

// Delicatessen y Acompañamientos Gourmet para Tablas
const DELICATESSEN_ITEMS = [
  {
    id: "miel-trufa-alba",
    name: "Miel de Acacia con Trufa Blanca de Alba (120g)",
    price: 18990,
    category: "acompanamiento",
    image: "img/products/miel-trufa.jpg",
    desc: "Gotas de oro aromático con lascas de trufa blanca, ideal para maridar con quesos azules y pecorinos maduros."
  },
  {
    id: "crackers-romero-artesanal",
    name: "Crackers de Masa Madre y Sal de Cahuil (150g)",
    price: 6990,
    category: "acompanamiento",
    image: "img/products/crackers-artesanal.jpg",
    desc: "Láminas crujientes horneadas en leña con romero silvestre y escamas de sal de mar de Cahuil, Pichilemu."
  },
  {
    id: "cuchillo-laguiole-fromage",
    name: "Cuchillo Maestro Fromager Laguiole de Aubrac",
    price: 42990,
    category: "accesorios",
    image: "img/products/cuchillo-laguiole.jpg",
    desc: "Acero forjado francés Sandvik 12C27 con punta bífida de servicio y mango en noble madera de nogal."
  }
];

// Formato de moneda chilena
function formatCLP(amount) {
  return "$" + Math.round(amount).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
}
